apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hi05gadhw-go
  janus-idp.io/tekton: hi05gadhw-go
  backstage.io/kubernetes-id: hi05gadhw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hi05gadhw-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
